apiVersion: v1
kind: Pod
metadata:
  name: pod-hostpath-secure
  namespace: audit-zone
spec:
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    seccompProfile:
      type: RuntimeDefault
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - name: data-volume
          mountPath: /mnt/data
      securityContext:
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        capabilities:
          drop:
            - ALL
  volumes:
    - name: data-volume
      emptyDir: {}
